### ISSUE TITLE
Show compass HUD with drone camera

### ISSUE THREAD

**Issue by Nekzuris** [mixMugz/msfs2020-uimod#14]
Maybe it's already possible and I'm doing something wrong, but I can't figure out how to get the compass in drone camera.

**Comment by mixMugz** [comment]
Unfortunately, this is not possible, because... limited by the game itself. HUD not showing in Drone camera mode

**Comment by Nekzuris** [comment]
Can something like this be done with developer mode ?

I just want to explore the map like on Google Earth.
