### ISSUE TITLE
Non-Latin characters won't show

### ISSUE THREAD

**Issue by ZiCongQ** [mixMugz/msfs2020-uimod#2]
Non-latin characters like Chinese Japanese or Korean names won't show up on the tinyplate.

**Comment by mixMugz** [comment]
It's showing without mod? Can you provide screenshots?

**Comment by ZiCongQ** [comment]
Here's the screenshot without mod, Chinese characters are showing just fine.
https://imgur.com/a/oqgVE0A

**Comment by mixMugz** [comment]
And also screen with mod can you provide please?

**Comment by mixMugz** [comment]
Try to remove:
font-family: Roboto; /* Change fontface */
in  IGM_AirTraffic.css

**Comment by ZiCongQ** [comment]
I have loaded in a font that supports chinese characters, and have changed the font-face to this font, now it shows CHinese cahracters just fine, before when a name has Chinese characters in it, for example "(something chinese)#1234" it would just show "#1234", i've changed to a font called Noto Sans CJK SC Medium weight. now its like this: https://imgur.com/a/VbkxHKm

**Comment by mixMugz** [comment]
So. Your issue is fixed? Close then
