### ISSUE TITLE
Any way to map the hide hud to mouse buttons?

### ISSUE THREAD

**Issue by fleps** [mixMugz/msfs2020-uimod#3]
Hi, not exactly an issue but, I know JS and tried to change the `InGameHud.js` to be activated by mouse button 4, but it didn't worked.

I've changed the evenListener to `onmousedown` and the even itself to event.button == 4, but didn't worked.

Do you know if the game uses something different to be able to capture the mouse buttons events? Is it possible somehow to debug this in game devmode, does it provide a way to reload a modified mod on the fly instead of having to restart the game?

Thanks!

**Comment by mixMugz** [comment]
Your questions are incorrectly addressed. They must be asked to the game developers. To intercept mouse control, you need to search for existing handlers in the main scripts and do by analogy.
