### ISSUE TITLE
Aircraft label but no POI?

### ISSUE THREAD

**Issue by Djeez2** [mixMugz/msfs2020-uimod#4]
Is it possible to show multiplayer nametags but not the POI markers?

**Comment by mixMugz** [comment]
Yes. Just turn Off POI markers in assistance screen

**Comment by Djeez2** [comment]
> Yes. Just turn Off POI markers in assistance screen

What I mean is, can I get use a key for the POI and a key for the labels to select them independently.

(btw, I would like to buy you a beer, but Paypal charges 2 Euro for a transfer. This is odd because all other donations I make to developers through Paypal do not have an additional charge. Do you know what's going on, or know a way to reduce transfer cost?)

**Comment by mixMugz** [comment]
For now i cant separate POI from IGM Traffic, it cause some distortion in styles. I'm searching solution but now i cant find. 
About Paypal i dont know why it add additional charge.

Try https://www.buymeacoffee.com/mugz

**Comment by Djeez2** [comment]
Thanks for the info.
Enjoy the coffee (maybe Paypal taxes beer ;-) )

**Comment by mixMugz** [comment]
> Thanks for the info.
> Enjoy the coffee (maybe Paypal taxes beer ;-) )

Thanks =)
