### ISSUE TITLE
Discord Link

### ISSUE THREAD

**Issue by DrewDaPilot** [mixMugz/msfs2020-uimod#5]
The discord icon that you included on the project page does not open up a link or allow me to join. If this could be corrected that would be much appreciated.

**Comment by mixMugz** [comment]
Thanks for report. Will look it later

**Comment by DrewDaPilot** [comment]
Hello, any update? I would love to join the discord to ask you a few questions personally.

Thanks,
Drew.

**Comment by mixMugz** [comment]
> Hello, any update? I would love to join the discord to ask you a few questions personally.
> 
> Thanks,
> Drew.

updated
